hours1 = int(input('Введите часы: '))
min1 = int(input('Введите минуты: '))
sec1 = int(input('Введите секунды: '))
hours2 = int(input('Введите часы: '))
min2 = int(input('Введите минуты: '))
sec2 = int(input('Введите секунды: '))
print((hours2 * 3600 + min2 * 60 + sec2) - (hours1 * 3600 + min1 * 60 + sec1))